package:
  name: pytetrad
  version: "5.3.0"
 
source:
  git_rev: v0.1
  git_url: https://github.com/bd2kccd/pytetrad.git
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - javabridge
    - numpy
    - pydot
    - pyparsing
    - GraphViz
  
about:
  home: https://github.com/bd2kccd/pytetrad
  license: LGPL >= 2.1
  license_file: LICENSE